name: Deploy to Firebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./next
        run: npm ci

      - name: Verify environment variables
        working-directory: ./next
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
        run: |
          echo "Checking environment variables..."
          missing_vars=()
          [[ -z "$NEXT_PUBLIC_FIREBASE_API_KEY" ]] && missing_vars+=("API Key")
          [[ -z "$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" ]] && missing_vars+=("Auth Domain")
          [[ -z "$NEXT_PUBLIC_FIREBASE_PROJECT_ID" ]] && missing_vars+=("Project ID")
          [[ -z "$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" ]] && missing_vars+=("Storage Bucket")
          [[ -z "$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" ]] && missing_vars+=("Messaging Sender ID")
          [[ -z "$NEXT_PUBLIC_FIREBASE_APP_ID" ]] && missing_vars+=("App ID")
          
          if [ ${#missing_vars[@]} -ne 0 ]; then
            echo "Error: Missing required environment variables:"
            printf '%s\n' "${missing_vars[@]}"
            exit 1
          fi
          echo "All required environment variables are set!"

      - name: Type check
        working-directory: ./next
        run: npm run typecheck

      - name: Build
        working-directory: ./next
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
          SQUARE_ACCESS_TOKEN: ${{ secrets.SQUARE_ACCESS_TOKEN }}
        run: npm run build

      - name: Deploy to Firebase
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEZBANI_14D1E }}
          channelId: live
          projectId: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
